import {useState,useEffect} from 'react'; import {api} from '../api';
const fmt=(n,d=2)=>Number(n||0).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
export default function TradeModal({coin,onClose,onSuccess}){
 const [side,setSide]=useState('BUY'),[quantity,setQuantity]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''),[wallet,setWallet]=useState(null);
 useEffect(()=>{api.wallet().then(setWallet).catch(()=>{})},[]);
 if(!coin)return null; const price=coin.price||0,total=parseFloat(quantity||0)*price,usdt=wallet?.assets?.find(a=>a.symbol==='USDT')?.quantity||0,balance=wallet?.assets?.find(a=>a.symbol===coin.base)?.quantity||0;
 const submit=async e=>{e.preventDefault();if(!quantity||parseFloat(quantity)<=0){setError('Enter a valid quantity.');return}setLoading(true);setError('');try{const data=await api.placeOrder({symbol:coin.symbol,side,quantity:parseFloat(quantity)});onSuccess?.({type:'success',msg:side+' '+quantity+' '+coin.base+' filled at $'+fmt(data.price)});onClose?.()}catch(err){setError(err.message||'Order failed')}finally{setLoading(false)}};
 const setPct=p=>{const max=side==='BUY'?usdt*p/100/price:balance*p/100;setQuantity(max>0?max.toFixed(6):'')};
 return <div className="modal-overlay" onClick={e=>e.target===e.currentTarget&&onClose?.()}><section className="modal-box"><div className="modal-header"><div className="asset-cell"><span className="asset-icon">{coin.base[0]}</span><div><strong>{coin.name}</strong><span className="asset-pair">{coin.base}/USDT</span></div></div><button className="icon-button" onClick={onClose} aria-label="Close">×</button></div><div className="trade-price"><span className="muted">Market price</span><strong>${price?fmt(price):'—'}</strong></div><div className="side-tabs"><button className={'btn '+(side==='BUY'?'btn-buy':'btn-ghost')} onClick={()=>{setSide('BUY');setError('')}}>Buy {coin.base}</button><button className={'btn '+(side==='SELL'?'btn-sell':'btn-ghost')} onClick={()=>{setSide('SELL');setError('')}}>Sell {coin.base}</button></div><div className="trade-balances"><div className="trade-balance"><span>USDT available</span><strong>${fmt(usdt)}</strong></div><div className="trade-balance"><span>{coin.base} available</span><strong>{fmt(balance,6)}</strong></div></div><form className="trade-form" onSubmit={submit}><div className="form-group"><label className="form-label">Quantity ({coin.base})</label><input className="form-input" type="number" min="0" step="any" value={quantity} placeholder="0.000000" onChange={e=>setQuantity(e.target.value)} required/></div><div className="quick-buttons">{[25,50,75,100].map(n=><button type="button" className="btn btn-ghost btn-sm" onClick={()=>setPct(n)} key={n}>{n}%</button>)}</div>{quantity&&parseFloat(quantity)>0&&<div className="order-summary"><div><span>Order</span><strong className={side==='BUY'?'positive':'negative'}>{side} {parseFloat(quantity).toFixed(6)} {coin.base}</strong></div><div><span>Estimated total</span><strong>${fmt(total)} USDT</strong></div></div>}{error&&<div className="error-box">{error}</div>}<button className={'btn btn-full '+(side==='BUY'?'btn-buy':'btn-sell')} disabled={loading||!price}>{loading?'Placing order…':side==='BUY'?'Place buy order':'Place sell order'}</button></form></section></div>;
}
