import { useState,useEffect,useCallback } from 'react';
import { api } from '../api'; import { usePricesWS } from '../useWebSocket';
const coins=[['BTCUSDT','Bitcoin','BTC'],['ETHUSDT','Ethereum','ETH'],['SOLUSDT','Solana','SOL'],['BNBUSDT','BNB','BNB'],['XRPUSDT','XRP','XRP'],['ADAUSDT','Cardano','ADA']];
const fmt=(n,d=2)=>Number(n||0).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
export default function MarketPage({onTrade}) {
 const [prices,setPrices]=useState({}),[stats,setStats]=useState({}),[flash,setFlash]=useState({}),[status,setStatus]=useState('connecting');
 const onPrice=useCallback(data=>{const p=parseFloat(data.price);setPrices(old=>{const dir=old[data.symbol]&&p>old[data.symbol]?'up':old[data.symbol]&&p<old[data.symbol]?'down':'';if(dir){setFlash(f=>({...f,[data.symbol]:dir}));setTimeout(()=>setFlash(f=>{const next={...f};delete next[data.symbol];return next}),600)}return {...old,[data.symbol]:p}});setStatus('connected')},[]);
 usePricesWS({onPrice,enabled:true}); useEffect(()=>{coins.forEach(([symbol])=>api.stats(symbol).then(s=>setStats(p=>({...p,[symbol]:s}))).catch(()=>{}))},[]);
 return <><div className="page-heading"><div><p className="eyebrow">Markets</p><h1>Live market prices</h1></div><div className="live-status"><i className={'status-dot status-'+(status==='connected'?'live':'connecting')}/>{status==='connected'?'Live feed':'Connecting'}</div></div><section className="panel"><div className="panel-header"><h2 className="panel-title">Spot markets</h2><span className="panel-subtitle">USDT pairs</span></div><div className="market-table-wrap"><table className="market-table"><thead><tr><th>Asset</th><th className="numeric">Last price</th><th className="numeric">24h change</th><th className="numeric">24h volume</th><th/></tr></thead><tbody>{coins.map(([symbol,name,base])=>{const s=stats[symbol],pct=parseFloat(s?.priceChangePercent);return <tr key={symbol}><td><div className="asset-cell"><span className="asset-icon">{base.slice(0,1)}</span><span><span className="asset-name">{name}</span><span className="asset-pair">{base}/USDT</span></span></div></td><td className={'numeric '+(flash[symbol]==='up'?'price-up':flash[symbol]==='down'?'price-down':'')}>{prices[symbol]?'$'+fmt(prices[symbol]):'—'}</td><td className={'numeric '+(pct>=0?'positive':'negative')}>{s?(pct>=0?'+':'')+pct.toFixed(2)+'%':'—'}</td><td className="numeric muted">{s?fmt(s.volume,0):'—'}</td><td className="trade-action"><button className="btn btn-ghost btn-sm" onClick={()=>onTrade({symbol,name,base,price:prices[symbol]})}>Trade</button></td></tr>})}</tbody></table></div></section></>;
}
