import {useState,useEffect} from 'react'; import {api} from '../api';
const fmt=(n,d=2)=>Number(n||0).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
export default function OrdersPage(){
 const [orders,setOrders]=useState([]),[loading,setLoading]=useState(true),[filter,setFilter]=useState('ALL');
 useEffect(()=>{api.orders().then(d=>{setOrders(d);setLoading(false)}).catch(()=>setLoading(false))},[]);
 if(loading)return <div className="loading"><div className="spinner"/><span>Loading orders</span></div>;
 const visible=filter==='ALL'?orders:orders.filter(o=>o.side===filter);
 return <><div className="page-heading"><div><p className="eyebrow">Orders</p><h1>Order history</h1></div><div className="filter-group">{['ALL','BUY','SELL'].map(f=><button key={f} className={'btn btn-sm '+(filter===f?'btn-primary':'btn-ghost')} onClick={()=>setFilter(f)}>{f}</button>)}</div></div><section className="panel"><div className="panel-header"><h2 className="panel-title">Filled orders</h2><span className="panel-subtitle">{visible.length} records</span></div>{visible.length?<div className="table-scroll"><table className="data-table"><thead><tr><th>ID</th><th>Pair</th><th>Side</th><th className="numeric">Quantity</th><th className="numeric">Price</th><th className="numeric">Total</th><th>Status</th><th>Date</th></tr></thead><tbody>{visible.map(order=><tr key={order.id}><td className="mono muted">#{order.id}</td><td><strong>{order.symbol}</strong></td><td className={order.side==='BUY'?'positive':'negative'}>{order.side}</td><td className="numeric">{fmt(order.quantity,6)}</td><td className="numeric">${fmt(order.price)}</td><td className="numeric">${fmt(order.totalAmount)}</td><td className="muted">{order.status}</td><td className="muted">{new Date(order.createdAt).toLocaleString('en-US',{month:'short',day:'2-digit',hour:'2-digit',minute:'2-digit'})}</td></tr>)}</tbody></table></div>:<div className="empty-state">No orders match this filter.</div>}</section></>;
}
