import {useState,useEffect,useCallback} from 'react'; import {api} from '../api'; import {usePortfolioWS} from '../useWebSocket';
const fmt=(n,d=2)=>Number(n||0).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
export default function PortfolioPage(){
 const [portfolio,setPortfolio]=useState(null),[prev,setPrev]=useState(null),[loading,setLoading]=useState(true),[status,setStatus]=useState('connecting');
 useEffect(()=>{api.portfolio().then(d=>{setPortfolio(d);setLoading(false)}).catch(()=>setLoading(false))},[]);
 const update=useCallback(d=>setPortfolio(p=>{if(p)setPrev(p.totalValueUsdt);return d}),[]); usePortfolioWS({onUpdate:update,onStatus:setStatus,enabled:true});
 if(loading)return <div className="loading"><div className="spinner"/><span>Loading portfolio</span></div>;
 const holdings=portfolio?.holdings||[], change=prev!==null?(portfolio?.totalValueUsdt||0)-prev:null;
 return <><div className="page-heading"><div><p className="eyebrow">Portfolio</p><h1>Portfolio overview</h1></div><div className="live-status"><i className={'status-dot status-'+(status==='connected'?'live':'connecting')}/>{status==='connected'?'Live updates':'Reconnecting'}</div></div><div className="portfolio-summary"><div className="summary-stat"><span className="summary-label">Total portfolio value</span><strong className="summary-value">${fmt(portfolio?.totalValueUsdt)}</strong><span className={'summary-note '+(change>=0?'positive':'negative')}>{change===null?'Updated with market prices':(change>=0?'+':'-')+'\$'+fmt(Math.abs(change),4)+' since last update'}</span></div><div className="summary-stat"><span className="summary-label">Assets held</span><strong className="summary-value">{holdings.length}</strong><span className="summary-note">Current positions</span></div><div className="summary-stat"><span className="summary-label">Base currency</span><strong className="summary-value">USDT</strong><span className="summary-note">Paper trading balance</span></div></div><section className="panel"><div className="panel-header"><h2 className="panel-title">Holdings</h2><span className="panel-subtitle">{holdings.length} assets</span></div>{holdings.length?<div className="table-scroll"><table className="data-table"><thead><tr><th>Asset</th><th className="numeric">Quantity</th><th className="numeric">Price</th><th className="numeric">Value</th><th className="numeric">Allocation</th></tr></thead><tbody>{holdings.map(h=>{const pct=portfolio.totalValueUsdt?(h.valueUsdt/portfolio.totalValueUsdt)*100:0;return <tr key={h.asset}><td><div className="asset-cell"><span className="asset-icon">{h.asset[0]}</span><strong>{h.asset}</strong></div></td><td className="numeric">{fmt(h.quantity,h.asset==='USDT'?2:6)}</td><td className="numeric muted">{h.asset==='USDT'?'—':'$'+fmt(h.priceUsdt)}</td><td className="numeric">${fmt(h.valueUsdt)}</td><td className="numeric">{pct.toFixed(1)}%</td></tr>})}</tbody></table></div>:<div className="empty-state">No holdings yet. Trade a market to build your portfolio.</div>}</section></>;
}
