import {useState,useEffect} from 'react'; import {api} from '../api';
const fmt=(n,d=2)=>Number(n||0).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
const labels={USDT:'Tether USD',BTC:'Bitcoin',ETH:'Ethereum',SOL:'Solana',BNB:'BNB',XRP:'XRP',ADA:'Cardano'};
export default function WalletPage({onToast}) {
 const [wallet,setWallet]=useState(null),[loading,setLoading]=useState(true),[amount,setAmount]=useState(''),[depositing,setDepositing]=useState(false);
 useEffect(()=>{api.wallet().then(d=>{setWallet(d);setLoading(false)}).catch(()=>setLoading(false))},[]);
 const deposit=async e=>{e.preventDefault();const value=parseFloat(amount);if(!value||value<=0)return;setDepositing(true);try{const data=await api.deposit({asset:'USDT',amount:value});setWallet(data);setAmount('');onToast?.({type:'success',msg:'Deposit completed: $'+fmt(value)+' USDT'});}catch(err){onToast?.({type:'error',msg:err.message||'Deposit failed'});}finally{setDepositing(false)}};
 if(loading)return <div className="loading"><div className="spinner"/><span>Loading wallet</span></div>;
 return <><div className="page-heading"><div><p className="eyebrow">Wallet</p><h1>Balances and funding</h1></div></div><div className="wallet-layout"><section className="panel"><div className="panel-header"><h2 className="panel-title">Asset balances</h2><span className="panel-subtitle">{wallet?.assets?.length||0} assets</span></div><div className="asset-list">{wallet?.assets?.map(asset=><div className="asset-row" key={asset.symbol}><div className="asset-cell"><span className="asset-icon">{asset.symbol[0]}</span><span><span className="asset-name">{asset.symbol}</span><span className="asset-pair">{labels[asset.symbol]||asset.symbol}</span></span></div><div className="balance"><strong>{fmt(asset.quantity,asset.symbol==='USDT'?2:6)}</strong><span>{asset.symbol}</span></div></div>)}</div></section><aside className="panel"><div className="panel-header"><h2 className="panel-title">Add paper funds</h2></div><form className="deposit-panel trade-form" onSubmit={deposit}><p className="note">Fund your simulated USDT balance to place paper trades. No real money is involved.</p><div className="form-group"><label className="form-label">Amount (USDT)</label><input className="form-input" type="number" min="1" step="100" placeholder="5000" value={amount} onChange={e=>setAmount(e.target.value)} required/></div><div className="quick-buttons">{[1000,5000,10000,50000].map(n=><button type="button" className="btn btn-ghost btn-sm" key={n} onClick={()=>setAmount(String(n))}>${n.toLocaleString()}</button>)}</div><button className="btn btn-primary btn-full" disabled={depositing||!amount}>{depositing?'Depositing…':'Deposit USDT'}</button></form></aside></div></>;
}
